# February 2021 {-}

## February 1 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The {dplyr} syntax is heavily inspired by <a href="https://twitter.com/hashtag/SQL?src=hash&amp;ref_src=twsrc%5Etfw">#SQL</a>, which means it is easy to *translate* the {dplyr} code to its equivalent query and this is supported in {dplyr} itself! 🙌 <a href="https://t.co/rjE4S2MK8o">https://t.co/rjE4S2MK8o</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/SffAhyRmWh">pic.twitter.com/SffAhyRmWh</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1356142364889395201?ref_src=twsrc%5Etfw">February 1, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 2 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In case you want to peruse how a ggplot (and its various layers) are built, you can use the {ggplot_build} function from {ggplot2}! 🏗 🚧 🦺 <a href="https://t.co/mIq2G3qAo8">https://t.co/mIq2G3qAo8</a><br><br>Useful also to investigate what are the aesthetic defaults for utilized {geom_}s.<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/UnQdpZYCJ8">pic.twitter.com/UnQdpZYCJ8</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1356499076385243138?ref_src=twsrc%5Etfw">February 2, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 3 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you want to get a quick overview of descriptive statistics for a numeric variable, {describe_distribution} from {parameters} 📦 is your friend 🙌 <a href="https://t.co/KlhJNsdL90">https://t.co/KlhJNsdL90</a><br><br>Also works with a {grouped_} dataframe from {dplyr} 👏<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/FoBio2p8yk">pic.twitter.com/FoBio2p8yk</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1356869403586031618?ref_src=twsrc%5Etfw">February 3, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 4 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you want to see a beautiful, colorful tree of your directory file structure, you can use {dir_tree} function from {fs} package! 🌳🌈 <a href="https://t.co/UpjcB7z7Qf">https://t.co/UpjcB7z7Qf</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/SlXAIcePoA">pic.twitter.com/SlXAIcePoA</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1357221055400730624?ref_src=twsrc%5Etfw">February 4, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 5 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you work a lot with web scraping and need to extract a particular node from HTML page, {html_nodes} from {rvest} 📦 is your friend 👯‍♀️<a href="https://t.co/ob6beJEkZN">https://t.co/ob6beJEkZN</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/kcouQ5rTfC">pic.twitter.com/kcouQ5rTfC</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1357602420101173252?ref_src=twsrc%5Etfw">February 5, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 6 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In a long script, it can become tiresome to keep duplicating the same object name when it is being self-assigned. <br><br>In such instances, the assignment pipe from {magrittr} 📦 proves handy! 👌<a href="https://t.co/NVHXfOZOI9">https://t.co/NVHXfOZOI9</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/3iGuHsUZjG">pic.twitter.com/3iGuHsUZjG</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1357973807479275523?ref_src=twsrc%5Etfw">February 6, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 7 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Often you might want to split an existing column into a combination of a few other columns and {separate} from {tidyr} 📦 is exactly what you are looking for! 🪄 <a href="https://t.co/imqGN7ridk">https://t.co/imqGN7ridk</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/wrSFpNtNeM">pic.twitter.com/wrSFpNtNeM</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1358324454238154752?ref_src=twsrc%5Etfw">February 7, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 8 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The {row_number} function from {dplyr} is a timesaver if you have to create a unique identifier for observations, especially if they belong to different groups 1️⃣2️⃣3️⃣<a href="https://t.co/XSagfpLHVg">https://t.co/XSagfpLHVg</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/JWb0W2XMjz">pic.twitter.com/JWb0W2XMjz</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1358679817135083524?ref_src=twsrc%5Etfw">February 8, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 9 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sometimes you just want to extract the source code present in the source document (e.g., Rmd) to a separate script, and {purl} from {knitr} 📦 makes that effortless! 🦪<a href="https://t.co/2lwSJ2HhKG">https://t.co/2lwSJ2HhKG</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/RpqD7zsQst">pic.twitter.com/RpqD7zsQst</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1359059621084880898?ref_src=twsrc%5Etfw">February 9, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 10 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Often you need to convert country names/codes from different conventions to standardized names, and {countrycode} function from the eponymous 📦 can handle most of such conversions! ⚙️<a href="https://t.co/QVF8hBe7BE">https://t.co/QVF8hBe7BE</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/RByINBRutU">pic.twitter.com/RByINBRutU</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1359404988599042050?ref_src=twsrc%5Etfw">February 10, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 11 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sometimes a factor level can be missing implicitly, you can make it explicit using {fct_explicit_na} function from {forcats} 📦 :<a href="https://t.co/GexbNwDl4L">https://t.co/GexbNwDl4L</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/7XI2z0cXR8">pic.twitter.com/7XI2z0cXR8</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1359774944629035008?ref_src=twsrc%5Etfw">February 11, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 12 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Cleaning column names so that they have a consistent pattern is probably the first and the most important step in data analysis and {clean_names} function from {janitor} 📦 is peerless in this regard 🧼 <a href="https://t.co/7w14DlhEvA">https://t.co/7w14DlhEvA</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/GmmVwHVrOA">pic.twitter.com/GmmVwHVrOA</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1360113008274505735?ref_src=twsrc%5Etfw">February 12, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 13 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The {markdown_} function family from {commonmark} 📦 can help you to convert markdown text into various formats (e.g., latex, html, etc.) ✍️ <a href="https://t.co/kADYv6J4lB">https://t.co/kADYv6J4lB</a><br><br>Can be a useful tool for teaching, say html, if one is already comfortable with rmarkdown.<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/AZyxYsPxvX">pic.twitter.com/AZyxYsPxvX</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1360492389299867653?ref_src=twsrc%5Etfw">February 13, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 14 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Some graphics 📦s (e.g. {hrbrthemes}) require special fonts. But it can be a pain to list and interrogate installed fonts.<br><br>The {system_fonts} function from {systemfonts} 📦 outputs a beautiful richly informative table with a one-line command 👏<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/aTiJdg7gZs">pic.twitter.com/aTiJdg7gZs</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1360873810459844610?ref_src=twsrc%5Etfw">February 14, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 15 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">When you just need to create a list of all possible combinations of values in a vector, {combn} function from {utils} 📦 comes in handy 🧰<a href="https://t.co/5tPzuFp1P9">https://t.co/5tPzuFp1P9</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/RoyLDraNty">pic.twitter.com/RoyLDraNty</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1361205063121833984?ref_src=twsrc%5Etfw">February 15, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 16 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">When you have to present results from a regression model in a well-formatted table, the {tbl_regression} function from {gtsummary} 📦 will be a serious time-saver 🗂<a href="https://t.co/EVoZ6ZRbgY">https://t.co/EVoZ6ZRbgY</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/q3MvqXIIog">pic.twitter.com/q3MvqXIIog</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1361574329327230976?ref_src=twsrc%5Etfw">February 16, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 17 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">In a deeply nested data structure (an object from JSON, e.g.), indexing can be a bit tedious in base-R.<br><br>The {pluck} function from {purrr} 📦 provides a less tiresome way to index 😌<a href="https://t.co/ePJ6HHVKm4">https://t.co/ePJ6HHVKm4</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/nhHEJKjkAu">pic.twitter.com/nhHEJKjkAu</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1361940327851036675?ref_src=twsrc%5Etfw">February 17, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 18 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">For comparing performance of different functions, or plain out of curiosity, sometimes we wish to benchmark an expression, and the {mark} function from {bench} 📦 makes this very easy! 🏋️‍♀️<a href="https://t.co/0qP7sY7J9c">https://t.co/0qP7sY7J9c</a><br><br>Note how {cor} is faster than {cor.test}.<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/8AGUg3rE4O">pic.twitter.com/8AGUg3rE4O</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1362314253563277313?ref_src=twsrc%5Etfw">February 18, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 19 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Nothing improves the readability of the code like a style guide, and this is exactly what {style_*} function family from {styler} 📦 does! 💅<br><br>The easiest thing to do is to run this function in the directory with your R scripts 🧹 <a href="https://t.co/Xjh4j4HuhQ">https://t.co/Xjh4j4HuhQ</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/NBhgffztFN">pic.twitter.com/NBhgffztFN</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1362663173929791491?ref_src=twsrc%5Etfw">February 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 20 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> has a native {IN} operator but sometimes you might miss the {NOT IN} operator from SQL. 😪<br><br>The {% raw %}{%nin%}{% endraw %} operator from {sjmisc} has you covered! 👏<a href="https://t.co/7IzXkPxlYD">https://t.co/7IzXkPxlYD</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/5dpgqHa8Vj">pic.twitter.com/5dpgqHa8Vj</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1363023605051850753?ref_src=twsrc%5Etfw">February 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 21 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you are well-versed in SQL and looking to learn {dplyr}, the {show_dplyr} function from {tidyquery} 📦 can be a helpful teaching assistant while translating from a SQL query to equivalent {dplyr} code! 👩‍🏫<a href="https://t.co/gT4ESz4h4y">https://t.co/gT4ESz4h4y</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/duKYJRuJN0">pic.twitter.com/duKYJRuJN0</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1363397748649848833?ref_src=twsrc%5Etfw">February 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 22 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Although a number of functions tend to have a {data} argument, some don’t. For such functions, the pipe operator (%&gt;%) from {magrittr} 📦 won’t work. <br><br>In such contexts, one can use the exposition pipe operator (%$%) 👏<a href="https://t.co/1RODRqilaL">https://t.co/1RODRqilaL</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/qxFmzJROKU">pic.twitter.com/qxFmzJROKU</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1363771242361282560?ref_src=twsrc%5Etfw">February 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 23 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The first important step of any data analysis workflow is to make sure that everything about your data “makes sense” and a few other tools out there do as good of a job describing your data as {skim} function from {skimr} 📦!<a href="https://t.co/vg3t4v8Ixq">https://t.co/vg3t4v8Ixq</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/FtpFi8ReZY">pic.twitter.com/FtpFi8ReZY</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1364099677491191808?ref_src=twsrc%5Etfw">February 23, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 24 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The infix operator (%||%) from {rlang} 📦 can be helpful for having a default value in case it is {NULL} 🪄<a href="https://t.co/qdMs5VAgjo">https://t.co/qdMs5VAgjo</a><br><br>Helpful for collaborative scripts or 📦 functions where users might enter different spellings to specify the same argument.<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/RDeKBpcFD1">pic.twitter.com/RDeKBpcFD1</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1364480027690217473?ref_src=twsrc%5Etfw">February 24, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 25 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Checking association between variables often involves carrying out correlation analysis and a few functions make this as easy as {correlation} from eponymous 📦<a href="https://t.co/VGZhhq9L0P">https://t.co/VGZhhq9L0P</a><br><br>Supports a huge variety of correlation methods.<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/piTCGqE5Ek">pic.twitter.com/piTCGqE5Ek</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1364831289069699072?ref_src=twsrc%5Etfw">February 25, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 26 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">If you want to conditionally select values in a dataframe, you can use {dplyr::filter}, but what if you want to do the same for a vector or a list?<br><br>The {keep} function from {purrr} does exactly that! 🐱 <a href="https://t.co/pAXndQ9Pl2">https://t.co/pAXndQ9Pl2</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/6yixL2ZKae">pic.twitter.com/6yixL2ZKae</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1365201178905174019?ref_src=twsrc%5Etfw">February 26, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 27 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">JSON data representation format is ubiquitous and some time we might need to convert our dataframe in R to a JSON object.<br><br>The {toJSON} function from {jsonlite} makes this a child’s play 👶<a href="https://t.co/0lOvOE19EW">https://t.co/0lOvOE19EW</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/PAbVQy4Kiz">pic.twitter.com/PAbVQy4Kiz</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1365574091764363267?ref_src=twsrc%5Etfw">February 27, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## February 28 {-}

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">When you are working with free-form survey inputs, you need to consider the possibility of mistakes in data entry.<br><br>In such contexts {stringdist_join} function from {fuzzyjoin} 📦 can save you headache while joining dataframes! ✌️<a href="https://t.co/HNANB6IjH2">https://t.co/HNANB6IjH2</a><a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> <a href="https://t.co/b3HT9Soqoa">pic.twitter.com/b3HT9Soqoa</a></p>&mdash; R Function A Day (@rfunctionaday) <a href="https://twitter.com/rfunctionaday/status/1365918960726769664?ref_src=twsrc%5Etfw">February 28, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
